services:
  - type: web
    name: writeback-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: SNOWFLAKE_USER
        value: ISAIDANI3
      - key: SNOWFLAKE_PASSWORD
        value: HJ2WbbxXR3gbKDN
      - key: SNOWFLAKE_ACCOUNT
        value: FHUXLIW-AW65453
      - key: SNOWFLAKE_WAREHOUSE
        value: TABLEAU
      - key: SNOWFLAKE_DATABASE
        value: TABLEAU
      - key: SNOWFLAKE_SCHEMA
        value: PUBLIC
